version: "3.8"
services:
  server:
    image: server_go
    ports:
      - "3000:3000"
    environment:
      HOST_NAME: postgres
      USER_NAME: postgres
      PASSWORD: postgres
      DB_NAME: postgres
      POST_PORT: 5432
      GOSERVER_PORT: :3000
      MEMC_PATH: memecached:11211
    depends_on:
      - postgres
      - memecached
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  memecached:
    image: memcached
    ports: 
      - "11211:11211"